# This is the workflow for building Qt5 on windows 10

name: Build Windows 10 Qt5

# Controls when action will run

on: 
  workflow_dispatch:
  
  #push:

jobs:
  build-windows-10-qt5:
    runs-on: self-hosted

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      
    #- name: Install wget
    #  run: |
    #      choco install wget
    
    #- name: Switch to D Disk
    #  shell: pwsh
    #  run: |
    #      C:
    #      pwd
    #- name: Install LLVM and Clang
    #  uses: KyleMayes/install-llvm-action@v1
    #  with:
    #    version: "10.0"
        
    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3
     
    - name: Download and Unzip Qt5 
      run: |
           Get-ExecutionPolicy -List
           cp -r ./patches D:
    #D:
    #wget https://download.qt.io/archive/qt/5.14/5.14.2/single/qt-everywhere-src-5.14.2.zip
    #unzip .\qt-everywhere-src-5.14.2.zip -d .\qt5
    # cd .\qt5\qt-everywhere-src-5.14.2
    # $7zPath = "C:\Program Files\7-Zip\7z.exe"
    # $zipfile = "D:\qt-everywhere-src-5.14.2.zip"
    # & "C:\Program Files\7-Zip\7z.exe" x $zipfile -oC:\qt5 -bsp1
    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3
      
    - name: Download and Unzip JOM  
      shell: pwsh
      run: |
           D:
           wget https://download.qt.io/official_releases/jom/jom_1_1_3.zip
           unzip .\jom_1_1_3.zip
           
    - name: Apply Patches
      shell: pwsh
      run: |
           D:
           cd .\qt5\qt-everywhere-src-5.14.2
           patch --verbose D:/qt5/qt-everywhere-src-5.14.2/qtwebengine/src/3rdparty/chromium/third_party/angle/BUILD.gn -i C:/patches/qt-5.14.2-angle.patch
           patch --verbose D:/qt5/qt-everywhere-src-5.14.2/qtwebengine/src/3rdparty/chromium/third_party/blink/renderer/platform/graphics/lab_color_space.h -i C:/patches/qt-5.14.2-lab-color-space.patch
           mkdir build
           
   # SECOND PATCH patch --verbose C:/qt5/qt-everywhere-src-5.14.2/qtwebengine/src/3rdparty/chromium/third_party/perfetto/include/perfetto/ext/base/circular_queue.h -i C:/patches/qt-5.14.2-circular-queue.patch
    - name: Build Qt5
      shell: pwsh
      run: |
           D:
           cd .\qt5\qt-everywhere-src-5.14.2
           cd build
           $path = $env:Path
           $newpath = $path.replace("D:\msys64\usr\bin","")
           $newpath = $newpath.replace("D:\Program Files\Git\usr\bin","")
           $newpath = ($newpath + ";D:\msys64\usr\bin"+";D:\Program Files\Git\usr\bin")
           $env:Path = $newpath
           ..\configure.bat -release -mp -pch -prefix "%CD%\qtbase" -opensource -confirm-license -nomake examples -nomake tests -opengl desktop -skip qtconnectivity -skip qtdoc -skip qtsensors -skip qtgamepad -skip qtlocation -skip qtspeech -skip qtscxml -skip qtwebsockets -skip qtremoteobjects -skip qtquickcontrols -skip qtquickcontrols2 -skip qtmacextras -skip qtlottie -skip qtserialbus -skip qttranslations -skip qtwebview -skip qtandroidextras -skip qtactiveqt -skip qtimageformats -skip qtwebchannel -skip qtwebview -skip qtx11extras -skip qtwayland -skip qtserialport -skip qtwebglplugin
           D:\jom.exe
    # nmake.exe
   
    #- name: Donwload Qt5 source and configure
    #  shell: cmd
    #  run: |
    #      git clone https://github.com/qt/qt5.git
    #      cd qt5
    #      git checkout v5.14.2
    #      git submodule update --init --recursive
    #      mkdir build
    #      cd build
    #      ..\configure.bat -release -opensource -confirm-license -nomake examples -nomake tests -opengl desktop -skip qtwebengine

    #- name: Create Build Directory
    #  shell: cmd
    #  run: |
    #    cd qt5
    #    cd build
        
    #- name: Checkout MSVC repository
    #  uses: ilammy/msvc-dev-cmd@v1
      
    #- name: Which directory
    #  run: |
    #    echo "This is the current directory"
    #    echo "============================="
    #    echo "%CD%"

    #- name: Build Qt5
    #  run: |
    #    namke 
        
    - name: Archive build artifact
      uses: actions/upload-artifact@v2
      with:
        name: qt-5.14.2-windows
        path: C:\qt5\qt-everywhere-src-5.14.2\build\qtbase
        
