# This is the workflow for building Qt5 on windows 10

name: Build Windows 10 Qt5

# Controls when action will run

on: 
  workflow_dispatch:
  
  push:

jobs:
  build-windows-10-qt5:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check if ActivePerl is installed
      shell: powershell
      run: |
        $perlExists = (Get-Command perl -ErrorAction SilentlyContinue) -ne $null
        echo "perlExists=$($perlExists)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        
    - name: Install activeperl
      shell: powershell
      if: env.perlExists == 'False'
      run: |
        choco install activeperl
        echo "C:\Perl64\bin" >> $GITHUB_PATH
        
    - name: Install python2
      shell: powershell
      run: |
        choco install python2
        echo "C:\Python27" >> $GITHUB_PATH
        echo "C:\Perl64\bin" >> $GITHUB_PATH

    - name: Configure Qt5 source code
      run: |
        $url = "https://download.qt.io/archive/qt/5.14/5.14.2/single/qt-everywhere-src-5.14.2.zip"
        $output = "qt-everywhere-src-5.14.2.zip"
        $progressPreference = 'Continue'
        $webRequest = @{
            Uri = $url
            OutFile = $output
            Progress = {
                param($webResponse)
                
                $bytesRecieved = $webResponse.BytesReceived
                $totalBytesToRecieve = $webResponse.TotalBytesToReceive
                $progress = [math]::Round(($bytesReceieved / $totalBytesToReceive)*100,2)
                
                Write-Progress -Activity "Downloading file..." -Status "Downloaded $bytesReceived of $totalBytesToReceive bytes ($progress%) -PercentComplete $progress"
            }
        }
        Invoke-WebRequest @webRequest
        Expand-Archive -Path qt-everywhere-src-5.14.2.zip -DestinationPath .

    - name: Configure and build Qt5
      run: |
        mkdir build
        cd build
        ..\qt-everywhere-src-5.14.2\configure -prefix %CD%\qtbase -opensource -confirm-license -nomake examples -nomake tests -opengl desktop
        nmake
        nmake install

    - name: Archive build artifact
      uses: actions/upload-artifact@v2
      with:
        name: qt-5.14.2-windows
        path: build\qtbase
        
