# Workflow for building GDCM 2.6.3 for windows

name: Build Windows 10 GDCM

# Controls when action will run

on:
  workflow_dispatch:
  
  #push:
  
jobs:
  build-windows-10-GDCM:
    runs-on: windows-2019
    
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      
    - name: Install wget
      run: |
        choco install wget
    
    - name: Download GDCM
      shell: pwsh
      run: |
        wget https://github.com/malaterre/GDCM/archive/refs/tags/v2.6.3.zip
    
    - name: Unzip GDCM
      shell: pwsh
      run: |
        unzip v2.6.3.zip
        
    - name: Configure GDCM
      shell: pwsh
      run: |
        cd GDCM-2.6.3
        mkdir build
        cd build
        cmake .. -DGDCM_STANDALONE=1
        #-DGDCM_BUILD_SHARED_LIBS:BOOL=ON -DGDCM_BUILD_TESTING:BOOL=ON -DGDCM_BUILD_SHARED_LIBS:BOOL=ON -DGDCM_INSTALL_NO_DOCUMENTATION=1 
        
    - name: Compile GDCM
      shell: pwsh
      run: |
        cd GDCM-2.6.3
        cd build
        cmake --build . --config Release
    
    - name: Test GDCM
      shell: pwsh
      run: |
        cd GDCM-2.6.3
        cd build
        ctest . -C Release
        
    - name: Packaging GDCM
      shell: pwsh
      run: |
        cd GDCM-2.6.3
        cd build
        cpack -C Release CPackConfig.cmake
        mkdir GDCM_2-6-3
        
