# This workflow builds HDF5

name: Build Windows 10 HDF5

# Controls when action will run

on:
  workflow_dispatch:
  
  push:
  
jobs:
  build-windows-10-hdf5:
    runs-on: windows-2019
    
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      
    - name: Install wget
      run: |
        choco install wget
        
    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3
    
    - name: Download HDF5
      shell: pwsh
      run: |
        wget https://github.com/HDFGroup/hdf5/archive/refs/tags/hdf5-1_12_2.zip
    
    - name: Unzip HDF5
      shell: pwsh
      run: |
        unzip .\hdf5-1_12_2.zip
        
    - name: Configuring HDF5
      shell: pwsh
      run: |
        cd hdf5-hdf5-1_12_2
        mkdir build
        cd build
        cmake -DBUILD_SHARED_LIBS:BOOL=ON -DHDF5_BUILD_HL_LIB:BOOL=ON -DHDF5_BUILD_CPP_LIB:BOOL=ON -DCMAKE_INSTALL_PREFIX=$HDF5_INSTALL_DIR -DCMAKE_BUILD_TYPE=Release ..
        
    - name: Compile HDF5
      shell: pwsh
      run: |
        cd hdf5-hdf5-1_12_2
        cd build
        cmake --build . --config Release
    
    - name: Testing HDF5
      shell: pwsh
      run: |
        cd hdf5-hdf5-1_12_2
        cd build
        ctest . -C Release
        
    - name: Packaging HDF5
      shell: pwsh
      run: |
        cd hdf5-hdf5-1_12_2
        cd build
        cpack -C Release CPackConfig.cmake
        mkdir HDF5_1-12-2
        mv *.zip ./HDF5_1-12-1
        mv *.exe ./HDF5_1-12-1
        mv *.msi ./HDF5_1-12-1
        
    #- name: Install HDF5
    #  shell: pwsh
    #  run: |
    #    $HDF5_INSTALL_DIR = "%CD%\hdf5"
    #    cd hdf5-hdf5-1_12_2
    #    cd build
    #    cmake --install . --config Release --prefix $HDF5_INSTALL_DIR
        
    - name: Archive Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: hdf5-1.12.2-windows
        path: ./hdf5-hdf5-1_12_2/HDF5_1-12-1
