# This is the workflow for building Qt5 on windows 10

name: Build Windows 10 Qt5

# Controls when action will run

on: 
  workflow_dispatch:
  
  #push:

jobs:
  build-windows-10-qt5:
    runs-on: self-hosted

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

      
    - name: Download Qt5 Source
      shell: cmd
      run: |
          git clone https://github.com/qt/qt5.git
          mkdir qt5_install
          cd qt5
          git checkout v5.15.1
          git submodule update --init --recursive

    #- name: Apply Patches
    #  shell: cmd
    #  run: |
    #       cd .\qt-everywhere-src-5.14.2
    #       patch --verbose qt5/qtwebengine/src/3rdparty/chromium/third_party/angle/BUILD.gn -i patches/qt-5.14.2-angle.patch
    #       patch --verbose qt5/qtwebengine/src/3rdparty/chromium/third_party/blink/renderer/platform/graphics/lab_color_space.h -i /patches/qt-5.14.2-lab-color-space.patch
          
    - name: Configure Qt5 Source
      shell: cmd
      run: |
          cd qt5
          set CL=/MP
          cmd /K "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
          mkdir build
          cd build
          ..\configure.bat -opensource -confirm-license --prefix=../../qt5_install -release -nomake examples -nomake tests -opengl desktop -skip qtconnectivity -skip qtdoc -skip qtsensors -skip qtgamepad -skip qtlocation -skip qtspeech -skip qtscxml -skip qtremoteobjects -skip qtquickcontrols -skip qtquickcontrols2 -skip qtmacextras -skip qtlottie -skip qtserialbus -skip qttranslations
          
    - name: Building Qt5
      shell: cmd
      run: |
          cd qt5
          cd build
          cmd /K "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
          jom.exe

    - name: Install Qt5
      shell: cmd
      run: |
          cd qt5
          cd build
          cmd /K "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
          jom.exe install
        
    - name: Archive build artifact
      uses: actions/upload-artifact@v2
      with:
        name: qt-5.15.10-windows
        path: ./qt5_install
        
