# Build SWIG for Windows 10

name: Build Windows 10 SWIG

# Controls when action will run

on:
  workflow_dispatch:
  
  #push:
  
jobs:
  build-windows-10-swig:
    runs-on: windows-2019
    
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3
      
    #- name: Setup MSVC
    #  uses: ilammy/msvc-dev-cmd@v1
    
    - name: Setup Msys
      uses: msys2/setup-msys2@v2
    
    - name: Install wget
      run: |
        choco install wget
    
    - name: Download SWIG
      shell: pwsh
      run: |
        wget https://github.com/swig/swig/archive/refs/tags/v3.0.12.zip
    
    - name: Unzip SWIG
      shell: pwsh
      run: |
        unzip ./v3.0.12.zip

    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3

    - name: Configuring SWIG
      shell: msys2 {0}
      run: |
        pacman -S --needed --noconfirm autoconf automake libtool make mingw-w64-ucrt-x86_64-gcc
        cd swig-3.0.12
        ./autogen.sh
        mkdir swig_install
        ./configure
        make
        make install
    
    - name: Test SWIG
      shell: msys2 {0}
      run: |
        cd swig-3.0.12
        make -k check
        
    - name: Archive Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: SWIG Install
        path: ./swig-3.0.12/swig_install
