# This workflow builds ITK

name: Build Windows 10 ITK

# Controls when action will run

on:
  workflow_dispatch:
  
  #push:
  
jobs:
  build-windows-10-itk:
    runs-on: windows-2019
    
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      
    - name: Install wget
      run: |
        choco install wget

    - name: Download ITK and Unzip
      shell: pwsh
      run: |
        C:
        wget https://github.com/InsightSoftwareConsortium/ITK/releases/download/v5.2.1/InsightToolkit-5.2.1.zip
        unzip InsightToolkit-5.2.1.zip
    
    - name: Configure ITK
      shell: pwsh
      run: |
        C:
        cd InsightToolkit-5.2.1
        mkdir build
        cd build
        mkdir ITK_5-2-1
        cmake -DCMAKE_INSTALL_PREFIX=C:/InsightToolkit-5.2.1/build/ITK_5-2-1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXAMPLES=0 -DModule_ITKReview=1 ..
        
    - name: Build ITK
      shell: pwsh
      run: |
        C:
        cd InsightToolkit-5.2.1
        cd build
        cmake --build . --config Release
    
    - name: Install ITK
      shell: pwsh
      run: |
        C:
        cd InsightToolkit-5.2.1
        cd build
        cmake --install . --config Release --prefix C:/InsightToolkit-5.2.1/build/ITK_5-2-1 
        
    - name: Archive Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: hdf5-1.12.2-windows
        path: ./hdf5-hdf5-1_12_2/build/HDF5_1-12-2
        
        
