# This is the workflow for building Qt5 on windows 10

name: Build Windows 10 Qt5

# Controls when action will run

on: 
  workflow_dispatch:
  
  push:

jobs:
  build-windows-10-qt5:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      
    - name: Donwload Qt5 source and configure
      shell: cmd
      run: |
          git clone https://github.com/qt/qt5.git
          cd qt5
          git checkout v5.14.2
          git submodule update --init --recursive
          mkdir build
          cd build
          ..\configure.bat -release -prefix "%CD%\qtbase" -opensource -confirm-license -nomake examples -nomake tests -opengl desktop -skip qtwebengine
          namke
          
    #- name: Create Build Directory
    #  shell: cmd
    #  run: |
    #    cd qt5
    #    cd build
        
    #- name: Checkout MSVC repository
    #  uses: ilammy/msvc-dev-cmd@v1
      
    #- name: Which directory
    #  run: |
    #    echo "This is the current directory"
    #    echo "============================="
    #    echo "%CD%"

    #- name: Build Qt5
    #  run: |
    #    namke 
        
    - name: Archive build artifact
      uses: actions/upload-artifact@v2
      with:
        name: qt-5.14.2-windows
        path: qt5\build\qtbase
        
