# This is the workflow for building Qt5 on windows 10

name: Build Windows 10 Qt5

# Controls when action will run

on: 
  workflow_dispatch:
  
  push:

jobs:
  build-windows-10-qt5:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Checkout Nmake  
      uses: ilammy/msvc-dev-cmd@v1
    
    - name: Get Explicit namke path
      shell: powershell
      run: |
        $msvcPath = (Get-ChildItem -Path "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC" | Sort-Object -Property FullName -Descending | Select-Object -First 1).FullName
        $nmakePath = Join-Path -Path $msvcPath -ChildPath "bin\Hostx64\x64\nmake.exe"
        echo "NMake Path: $nmakePath"
        echo "NMAKE_PATH=$nmakePath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    
    - name: Call namke
      shell: powershell
      run: namke /?
      
    - name: Check if ActivePerl is installed
      shell: powershell
      run: |
        $perlExists = (Get-Command perl -ErrorAction SilentlyContinue) -ne $null
        echo "perlExists=$($perlExists)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        
    - name: Install activeperl
      shell: powershell
      if: env.perlExists == 'False'
      run: |
        choco install activeperl
        echo "C:\Perl64\bin" >> $GITHUB_PATH
        
    - name: Install python2
      shell: powershell
      run: |
        choco install python2
        echo "C:\Python27" >> $GITHUB_PATH
        echo "C:\Perl64\bin" >> $GITHUB_PATH
    - name: Install cmake
      shell: powershell
      run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          refreshenv
    - name: Install LLVM
      shell: powershell
      run: |
          choco install llvm --version=12.0.0
          refreshenv
    - name: Download Qt5 source code
      shell: powershell
      run: |
          git clone https://github.com/qt/qt5.git
          cd qt5
          git checkout v5.14.2
          git submodule update --init --recursive
          mkdir build
          cd build
          ..\configure.bat -release -prefix "%CD%\qtbase" -opensource -confirm-license -nomake examples -nomake tests -opengl desktop -skip qtwebengine
          namke

    - name: Archive build artifact
      uses: actions/upload-artifact@v2
      with:
        name: qt-5.14.2-windows
        path: qt5\build\qtbase
        
