# This is the workflow for building Qt5 on windows 10

name: Build Windows 10 Qt5

# Controls when action will run

on: 
  workflow_dispatch:
  
  #push:

jobs:
  build-windows-10-qt5:
    runs-on: windows-2019

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      
    - name: Install wget
      run: |
          choco install wget
    
    - name: Switch to C Disk
      shell: pwsh
      run: |
          C:
          pwd
    #- name: Install LLVM and Clang
    #  uses: KyleMayes/install-llvm-action@v1
    #  with:
    #    version: "10.0"
        
    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3
     
    - name: Download and Build Qt5 
      shell: pwsh
      run: |
           cp -r ./patches C:
           C:
           wget https://download.qt.io/archive/qt/5.14/5.14.2/single/qt-everywhere-src-5.14.2.zip
           unzip .\qt-everywhere-src-5.14.2.zip -d .\qt5
           cd .\qt5\qt-everywhere-src-5.14.2
           
    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3
      
    - name: Apply Patches
      shell: pwsh
      run: |
           C:
           cd .\qt5\qt-everywhere-src-5.14.2
           patch --verbose C:/qt5/qt-everywhere-src-5.14.2/qtwebengine/src/3rdparty/chromium/third_party/angle/BUILD.gn -i C:/patches/qt-5.14.2-angle.patch
           patch --verbose C:/qt5/qt-everywhere-src-5.14.2/qtwebengine/src/3rdparty/chromium/third_party/blink/renderer/platform/graphics/lab_color_space.h -i C:/patches/qt-5.14.2-lab-color-space.patch
           mkdir build
           
   # SECOND PATCH patch --verbose C:/qt5/qt-everywhere-src-5.14.2/qtwebengine/src/3rdparty/chromium/third_party/perfetto/include/perfetto/ext/base/circular_queue.h -i C:/patches/qt-5.14.2-circular-queue.patch
    - name: Build Qt5
      shell: pwsh
      run: |
           C:
           cd .\qt5\qt-everywhere-src-5.14.2
           cd build
           $path = $env:Path
           $newpath = $path.replace("C:\msys64\usr\bin","")
           $newpath = $newpath.replace("C:\Program Files\Git\usr\bin","")
           $newpath = ($newpath + ";C:\msys64\usr\bin"+";C:\Program Files\Git\usr\bin")
           $env:Path = $newpath
           ..\configure.bat -release -prefix "%CD%\qtbase" -opensource -confirm-license -nomake examples -nomake tests -opengl desktop #-skip qtbluetooth -skip qtmultimedia -skip qtpositioning -skip qtwebview -skip qtwebsockets -skip qttexttospeech -skip qtsensors 
           nmake.exe
   
    #- name: Donwload Qt5 source and configure
    #  shell: cmd
    #  run: |
    #      git clone https://github.com/qt/qt5.git
    #      cd qt5
    #      git checkout v5.14.2
    #      git submodule update --init --recursive
    #      mkdir build
    #      cd build
    #      ..\configure.bat -release -opensource -confirm-license -nomake examples -nomake tests -opengl desktop -skip qtwebengine

    #- name: Create Build Directory
    #  shell: cmd
    #  run: |
    #    cd qt5
    #    cd build
        
    #- name: Checkout MSVC repository
    #  uses: ilammy/msvc-dev-cmd@v1
      
    #- name: Which directory
    #  run: |
    #    echo "This is the current directory"
    #    echo "============================="
    #    echo "%CD%"

    #- name: Build Qt5
    #  run: |
    #    namke 
        
    - name: Archive build artifact
      uses: actions/upload-artifact@v2
      with:
        name: qt-5.14.2-windows
        path: C:\qt5\qt-everywhere-src-5.14.2\build\qtbase
        
