# This is the workflow for building Qt5 on windows 10

name: Build Windows 10 Qt5

# Controls when action will run

on: 
  workflow_dispatch:
  
  #push:

jobs:
  build-windows-10-qt5:
    runs-on: self-hosted

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

      
    - name: Download Qt5 Source
      shell: cmd
      run: |
          git clone https://github.com/qt/qt5.git
          mkdir qt5_install
          cd qt5
          git checkout v5.15.10
          git submodule update --init --recursive
          
    - name: Configure Qt5 Source
      shell: cmd
      run: |
          cd qt5
          set CL=/MP
          cmd /K vcvarsall.bat x64
          mkdir build
          cd build
          ..\configure.bat -opensource -confirm-license --prefix=../../qt5_install -release -nomake examples -nomake tests -opengl desktop -skip qtconnectivity -skip qtdoc -skip qtsensors -skip qtgamepad -skip qtlocation -skip qtspeech -skip qtscxml -skip qtremoteobjects -skip qtquickcontrols -skip qtquickcontrols2 -skip qtmacextras -skip qtlottie -skip qtserialbus -skip qttranslations
          
    - name: Building Qt5
      shell: cmd
      run: |
          cd qt5
          cd build
          cmd /K vcvarsall.bat x64
          jom.exe
    
        
    - name: Archive build artifact
      uses: actions/upload-artifact@v2
      with:
        name: qt-5.15.10-windows
        path: ./qt5_install
        
