# This is the workflow for building Qt5 on windows 10

name: Build Windows 10 Qt5

# Controls when action will run

on: 
  workflow_dispatch:
  
  push:

jobs:
  build-windows-10-qt5:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
        
    - name: Call vcvar64
      shell: cmd
      run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          
    - name: Donwload Qt5 source and configure
      run: |
          git clone https://github.com/qt/qt5.git
          cd qt5
          git checkout v5.14.2
          git submodule update --init --recursive
          mkdir build
          cd build
          ..\configure.bat -release -prefix "%CD%\qtbase" -opensource -confirm-license -nomake examples -nomake tests -opengl desktop -skip qtwebengine
          nmake
        
    - name: Archive build artifact
      uses: actions/upload-artifact@v2
      with:
        name: qt-5.14.2-windows
        path: qt5\build\qtbase
        
